name: Pytest-CI

on:
  push:
  pull_request:

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        poetry config virtualenvs.in-project true
    
    - name: Install Dependencies
      run: poetry install --no-interaction

    - name: Lint check
      run: |
        poetry run isort . --diff
        poetry run black --check --diff .

    - name: Run Tests
      run: poetry run pytest tests
